.onAttach <- function(libname, pkgname) {
	  packageStartupMessage(
				   "Welcome to SNPSelection package! This package is mainly used to select the SNP with the highest information content for chip design. ",
				      "Use the function location_sel_SNP(SNP_number_want). ",
				      "For help, please contact: lxb@yzu.edu.cn.\n",
				         "You need to provide all the raw files and map files (--maf 0.05 --geno 0) ",
				         "that are generated by plink (In the running directory!!!) and remove the first line ",
					 "and the first six columns of the raw file."
	)				 
}
